import { CalendarDays, ChevronLeft, ChevronRight, ChevronsLeft, ChevronsRight, X } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';

const weekDays=['一','二','三','四','五','六','日'];
const iso=(value:Date)=>`${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,'0')}-${String(value.getDate()).padStart(2,'0')}`;
const fromIso=(value:string)=>{const [year,month,day]=value.split('-').map(Number);return new Date(year,month-1,day)};
const monthStart=(value:Date)=>new Date(value.getFullYear(),value.getMonth(),1);
const addMonths=(value:Date,amount:number)=>new Date(value.getFullYear(),value.getMonth()+amount,1);

function CalendarMonth({month,start,end,onSelect}:{month:Date;start:string;end:string;onSelect:(day:string)=>void}) {
  const days=useMemo(()=>{const first=monthStart(month);const mondayOffset=(first.getDay()+6)%7;const cursor=new Date(first);cursor.setDate(cursor.getDate()-mondayOffset);return Array.from({length:42},(_,index)=>{const day=new Date(cursor);day.setDate(cursor.getDate()+index);return day})},[month]);
  return <div className="calendar-month"><div className="calendar-month-title">{month.getFullYear()} 年 {month.getMonth()+1} 月</div><div className="week-row">{weekDays.map(day=><span key={day}>{day}</span>)}</div><div className="days-grid">{days.map(day=>{const value=iso(day);const outside=day.getMonth()!==month.getMonth();const inRange=Boolean(start&&end&&value>start&&value<end);const isStart=value===start,isEnd=value===end;return <button key={value} aria-label={`${day.getFullYear()}年${day.getMonth()+1}月${day.getDate()}日`} className={`${outside?'outside ':''}${inRange?'in-range ':''}${isStart?'range-start ':''}${isEnd?'range-end ':''}`} onClick={()=>onSelect(value)}><span>{day.getDate()}</span></button>})}</div></div>;
}

export function DateRangePicker({start,end,draftStart,draftEnd,open,onToggle,onStartChange,onEndChange,onApply}:{start:string;end:string;draftStart:string;draftEnd:string;open:boolean;onToggle:()=>void;onStartChange:(value:string)=>void;onEndChange:(value:string)=>void;onApply:()=>void}) {
  const [visibleMonth,setVisibleMonth]=useState(()=>monthStart(fromIso(start)));
  const [awaitingEnd,setAwaitingEnd]=useState(false);
  useEffect(()=>{if(open){setVisibleMonth(monthStart(fromIso(draftStart||start)));setAwaitingEnd(false)}},[open]);
  const selectDay=(value:string)=>{if(!awaitingEnd||!draftStart||draftEnd){onStartChange(value);onEndChange('');setAwaitingEnd(true);return}if(value<draftStart){onStartChange(value);return}onEndChange(value);setAwaitingEnd(false)};
  const preset=(days:number)=>{const finish=new Date();const begin=new Date(finish);begin.setDate(begin.getDate()-days+1);onStartChange(iso(begin));onEndChange(iso(finish));setVisibleMonth(monthStart(begin));setAwaitingEnd(false)};
  const currentMonth=()=>{const finish=new Date();const begin=monthStart(finish);onStartChange(iso(begin));onEndChange(iso(finish));setVisibleMonth(begin);setAwaitingEnd(false)};
  const sinceOpening=()=>{const begin=fromIso('2026-07-01');const finish=new Date();onStartChange(iso(begin));onEndChange(iso(finish));setVisibleMonth(monthStart(begin));setAwaitingEnd(false)};
  return <div className="date-wrap"><button className="date range-trigger" onClick={onToggle}><CalendarDays size={18}/><span><small>统计周期</small><b>{start}</b><em>至</em><b>{end}</b></span></button>{open&&<div className="range-calendar-popover"><div className="range-calendar-title"><div><h3>选择统计日期</h3><p>{awaitingEnd?'已选择开始日，请选择结束日期':'先点击开始日期，再点击结束日期'}</p></div><button aria-label="关闭日期选择" onClick={onToggle}><X size={19}/></button></div><div className="range-calendar-body"><div className="calendar-presets"><b>快捷选择</b><button onClick={()=>preset(7)}>最近 7 天</button><button onClick={()=>preset(14)}>最近 14 天</button><button onClick={()=>preset(30)}>最近 30 天</button><button onClick={currentMonth}>本月至今</button><button onClick={sinceOpening}>建店至今</button></div><div className="calendar-pane"><div className="calendar-navigation"><div><button aria-label="上一年" title="上一年" onClick={()=>setVisibleMonth(value=>addMonths(value,-12))}><ChevronsLeft size={20}/></button><span>年</span><button aria-label="下一年" title="下一年" onClick={()=>setVisibleMonth(value=>addMonths(value,12))}><ChevronsRight size={20}/></button></div><strong>{visibleMonth.getFullYear()} 年 {visibleMonth.getMonth()+1} 月 — {addMonths(visibleMonth,1).getFullYear()} 年 {addMonths(visibleMonth,1).getMonth()+1} 月</strong><div><button aria-label="上个月" title="上个月" onClick={()=>setVisibleMonth(value=>addMonths(value,-1))}><ChevronLeft size={21}/></button><span>月</span><button aria-label="下个月" title="下个月" onClick={()=>setVisibleMonth(value=>addMonths(value,1))}><ChevronRight size={21}/></button></div></div><div className="dual-calendar"><CalendarMonth month={visibleMonth} start={draftStart} end={draftEnd} onSelect={selectDay}/><CalendarMonth month={addMonths(visibleMonth,1)} start={draftStart} end={draftEnd} onSelect={selectDay}/></div></div></div><div className="range-calendar-footer"><span>已选区间：<b>{draftStart||'请选择'}</b><em>至</em><b>{draftEnd||'请选择'}</b></span><div><button className="calendar-cancel" onClick={onToggle}>取消</button><button className="calendar-apply" disabled={!draftStart||!draftEnd} onClick={onApply}>应用日期</button></div></div></div>}</div>;
}
